### ISSUE TITLE
Is stream-to-mmio the AXI4-Stream or a stream emulated via the AXI4-Lite.

### ISSUE THREAD

**Issue by m-kru** [abs-tudelft/vhdmmio#17]
From the vhdmmio general documentation:

> vhdmmio concerns itself with the generation of register files. To vhdmmio, a register file is an AXI4-lite slave, consisting of any number of fields, occupying the full 4GiB address range provided by AXI4-lite for as far as the register file is concerned. Normally, not the whole 4GiB range will be accessible; this is up to the unit that's generating the addresses. For the "toplevel" register file, this would normally be some shell or bus infrastructure that only maps a certain address range to it.

From the `stream-to-mmio` documentation:

> Fields with stream-to-mmio behavior interface with an incoming AXI4 stream. When the incoming AXI4 stream is valid and the internal register for the field is not, the stream is handshaked and the data is put in the register. The MMIO bus can then read from the field to fetch the data, automatically invalidating the internal register to let the cycle repeat. The field cannot be written by the bus.

It is a bit confusing what `stream-to-mmio` actually is. Is "AXI4 stream" the AXI4-Stream as described in the AMBA AXI-Stream Protocol Specification, or maybe it is just a logical stream emulated using AXI4-Lite?

**Comment by jvanstraten** [comment]
I think you're overthinking it. It's just a convenience register type to connect a back-pressured stream to software. It should give you a hardware interface like this:

 - valid: in std_logic;
 - ready: out std_logic;
 - data: in [field type];

When the stream source connected to this interface first sends a value (valid=1) the register file acknowledges it (ready=1) and then blocks further transfers (ready=0). The received value is stored in a holding register, which can then be read via the AXI4-lite bus like any other register. Once read, the holding register is cleared and the stream is unblocked again (ready=1) to accept the next transfer. So you can "pop" from a hardware stream source by just reading the register.

I don't clearly remember what happens when the register is read when no data is in the holding register. I think that behavior is configurable (bus error, block the bus, etc)?

The ready/valid handshake is the same as what's used by AXI-stream, so I generally just lazily call them AXI streams. But technically speaking, the AXI-stream specification has a bunch more layers on top for specifically byte-oriented streaming, which this interface does _not_ support.
