### ISSUE TITLE
Generating C/C++/Python files

### ISSUE THREAD

**Issue by m-kru** [abs-tudelft/vhdmmio#8]
How to generate code for C, C++ or Python accessing the registers? I have installed the latest version from PyPI, but it looks like the `vhdmmio` has no parameters to generate files for these languages.

**Comment by jvanstraten** [comment]
It might very well not be implemented. It was a planned feature at the time and the code is structured in a way to support it (easily, in fact), but I probably just never got around to doing it.

**Comment by m-kru** [comment]
@jvanstraten have you abandoned the project in favor of something else?

**Comment by jvanstraten** [comment]
Yes and no. My career took me to companies that didn't want to step away from their already-developed in-house/proprietary solutions, but if at some point it makes sense for me to use it again or someone comes along to take over development long-term, I'll for sure pick up from where I left off. It's such a sad situation in the hardware world that everyone keeps reinventing their own wheels or buying/selling generally crap-quality IP for $$$$$ rather than embracing the open-source way... but here we are.
